---
title: How to add heading anchors to your Hugo site
date: 2021-09-11
lastmod: 2021-09-12
description: Learn how to rate up your SEO score and SEO rankings by adding anchors and hashes to your Hugo website.
slug: hugo-heading-anchors-and-hashes
schemas: [BlogPosting]
---
:toc:
:source-highlighter:
:icons: font

// /articles/hugo-heading-anchors-and-hashes/

Your articles are quite long for a better search engine ranking and you want to provide your visitors a way to directly link to sections on your pages?

Link hashes are the technical feature you are looking for, these are the part of the URL starting with a hashtag and referring to specific element on your page with the `id` of the `hash` name.

[source, url]
----
https://hugoseotheme.com/some/awesome/posting/#hash
----

There are quite a lot pages out there which let their visitors grab these section links on their page, which is for example a super feature in terms of sharing web content.

The anchor links are added beside the headlines on the page for best reference, for visualisation also the `#` is used, looking on the link example above you should know why. 😉

So you also want to upgrade your Hugo website by adding heading anchors, right? The _Hugo SEO Theme_ automatically adds links to each headline of your articles and blog postings. Your visitors will be able to directly jump to all of your sections to get unique permalinks for direct linking. Here you go right to the official link:{{< ref "/buy.adoc" >}}[_Hugo SEO Theme_].

NOTE: Check out the link:{{< ref "/demos" >}}[demos] to get an idea of the look and feel of the heading anchors provided by the _Hugo SEO Theme_.
