baseURL:          https://hugoseotheme.com
languageCode:     en-us
title:            Hugo SEO Theme
# theme:            [../../hugo-theme-seo, ../../hugo-theme-component-asciidoctor-skin, ../../hugo-theme-component-structured-data]
theme:          [hugo-theme-seo, hugo-theme-component-asciidoctor-skin, hugo-theme-component-structured-data]

disableKinds:     [taxonomy, taxonomyTerm]

ignoreFiles:      [features]

enableRobotsTXT:  true

# enableGitInfo:  true

# sectionPagesMenu: main

menu:
  main:
    - name:       "The Theme"
      weight:     1
      identifier: "hugo-seo-theme"
      url:        "/hugo-seo-theme/"
    - name:       "Demos"
      weight:     2
      identifier: "demos"
      url:        "/demos/"
    - name:       "Documentation"
      weight:     3
      identifier: "docs"
      url:        "/docs/"
