baseURL:          https://hugoseotheme.com
languageCode:     en-us
title:            Hugo SEO Theme
<<<<<<< HEAD
# theme:
#   - ../../hugo-theme-seo
#   - ../../hugo-theme-component-asciidoctor-skin
#   - ../../hugo-theme-component-structured-data
theme:
  - hugo-theme-seo
  - hugo-theme-component-asciidoctor-skin
  - hugo-theme-component-structured-data
=======
theme:
  - ../../hugo-theme-seo
  - ../../hugo-theme-component-asciidoctor-skin
  - ../../hugo-theme-component-structured-data
# theme:
#   - hugo-theme-seo
#   - hugo-theme-component-asciidoctor-skin
#   - hugo-theme-component-structured-data
>>>>>>> 8c3355b02a0b53c0cfe9a195967ce50063d3fc71

disableKinds:     [taxonomy, taxonomyTerm]

ignoreFiles:      [features]

enableRobotsTXT:  true

# enableGitInfo:  true

# sectionPagesMenu: main

menu:
  main:
    - name:       "The Theme"
      weight:     1
      identifier: "hugo-seo-theme"
      url:        "/hugo-seo-theme/"
    - name:       "Demos"
      weight:     2
      identifier: "demos"
      url:        "/demos/"
    - name:       "Documentation"
      weight:     3
      identifier: "docs"
      url:        "/docs/"
    - name:       "Articles"
      weight:     2
      identifier: "articles"
      url:        "/articles/"
