author:          David Wolf
titleSeparator:  —
themeColor:      '#ff6961'

icons:
  favicon:       favicon.svg
  touchIcon:     favicon.svg
  maskIcon:      mask-icon.svg

widgetAreas:
  sidebarMobile:
    area:
      symbol:    '☰'
    widgets:
      - widget:  core/toc
      - widget:  core/menu
      - widget:  core/meta
  headerTop:
    widgets:
      - widget:  core/breadcrumbs
  # headerSub:
  #   widgets:
  #     - widget:  core/meta
  sidebarLeft:
    widgets:
      # - widget:  core/menusections
      - widget:  core/menu
      - widget:  core/meta
  sidebarRight:
    widgets:
      - widget:  core/toc
  footer:
    widgets:
      - widget:  share/editongithub
        user:    hugoseotheme
        repo:    hugoseotheme.com
        branch:  master
      - widget:  core/breadcrumbs
