name = 'Sales Funnel'
license = 'MIT'
licenselink = './LICENSE.txt'
description = 'desc'
homepage = ''
tags = ['landing', 'funnel', 'sale']
features = ['Google Tag Manager', 'Google Analytics']
# min_version = '0.59.1'

[author]
  name = 'David Wolf'
  homepage = 'davidwolf.dev'
