baseURL:       https://hugoseotheme.com
languageCode:  en-us
title:         Hugo SEO Theme
# theme:         ['../../../hugo-theme-seo', '../../../hugo-theme-component-structured-data']
theme:         ['hugo-theme-seo', hugo-theme-component-structured-data]

disableKinds:  ['taxonomy', 'taxonomyTerm']

menu:
  main:
    - identifier: 'examples'
      url:     '/examples/'
  footer:
    - identifier: 'legal'
      url:     '/legal/'
    - identifier: 'privacy'
      url:     '/privacy/'
