baseURL:       https://hugoseotheme.com
languageCode:  en-us
title:         Hugo SEO Theme
theme:         ['../../../hugo-seo-theme', hugo-theme-component-structured-data]

disableKinds:  ['taxonomy', 'taxonomyTerm']

menu:
  main:
    - identifier: 'posts'
      url:     '/posts/'
  footer:
    - identifier: 'legal'
      url:     '/legal/'
    - identifier: 'privacy'
      url:     '/privacy/'
